"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/Header/page'
import menuContext from './app_context/appContext'
import Menu from './components/Menu/page'
import {useState} from 'react';
import { store } from '../store/store'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Tunnel App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [submenu,setsubMenu] = useState(false);
  const [appData,setAppData] = useState();
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider store={store}>
          <Header/>
          {submenu?<Menu/>:''}
          {children }
      </Provider>
      </body>
    </html>
  )
}
