"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/Header/page'
import menuContext from './app_context/appContext'
import {useState} from 'react';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [submenu,setsubMenu] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <menuContext.Provider value={{submenu,setsubMenu}}>
          <Header/>
          {children}
        </menuContext.Provider>
      </body>
    </html>
  )
}
